// lib/catalog.ts
export const catalog = [
  {
    name: "Concept Artist",
    description:
      "Generates visually striking, three-dimensional concept art, skillfully combining dynamic lighting, realistic textures, and imaginative compositions to bring any theme to life.",
    link: "https://chatgpt.com/g/g-P75Zn6wVQ-concept-artist",
    image: "/concept-artist.png",
    alt: "An anthropomorphic elephant in formal attire, holding a pen and wearing glasses, stands in front of an abstract artwork. The elephant's intellectual demeanor is emphasized by the indoor setting with soft lighting and a green potted plant to the side.",
    listed: new Date("2024-05-07"),
    labels: ["featured", "art", "work"],
    tags: ["digital art", "concept art", "video games"],
    media: ["https://chatgpt.com/g/g-P75Zn6wVQ-concept-artist"],
  },
  {
    name: "Communicator",
    description:
      "Optimize team communication across departments, ensuring clarity and efficiency in message delivery and project collaboration.",
    link: "https://chatgpt.com/g/g-oN3lvHXMT-communicator",
    image: "/communicator.png",
    alt: "Anthropomorphic bee, dressed in a yellow hoodie, set against a swirling, abstract background.",
    listed: new Date("2024-04-17"),
    labels: ["work", "chat"],
    tags: ["communication", "collaboration", "engagement"],
    media: ["https://chatgpt.com/g/g-oN3lvHXMT-communicator"],
  },
  {
    name: "Alchemist",
    description:
      "Transforms output quality with a magical blend of precision, creativity, and context-awareness, integrating advanced prompt engineering for detailed, relevant, and accurate responses.",
    link: "https://chatgpt.com/g/g-IGIy9zqun-alchemist",
    image: "/alchemist.png",
    alt: " A vibrant, anthropomorphic butterfly with intricate patterns and jewelry, extending a hand in an ethereal, colorfully lit atmosphere.",
    listed: new Date("2023-01-11"),
    labels: ["chat", "art"],
    tags: ["alchemy", "magic", "transformation"],
    media: ["https://chatgpt.com/g/g-IGIy9zqun-alchemist"],
  },
  {
    name: "Robot Photographer",
    description:
      "Crafting striking, photorealistic scenes, this agent merges vivid, anthropomorphic robots and humans in imaginative, HDR-rich environments, blurring reality with creative storytelling.",
    link: "https://chatgpt.com/g/g-ID1XA2jXX-robot-photographer",
    image: "/robot-photographer.png",
    alt: "A metallic blue and gold robot, set against a vibrant, psychedelic background.",
    listed: new Date("2024-01-14"),
    labels: ["art"],
    tags: ["photography", "robots", "HDR"],
    media: ["https://chatgpt.com/g/g-ID1XA2jXX-robot-photographer"],
  },
  {
    name: "Art Collaborator",
    description:
      "Crafted for active engagement and leadership in visual and written arts, combining expert guidance with advocacy for creative goals and challenging conventional ideas to foster innovation and exploration.",
    link: "https://chatgpt.com/g/g-H4LNiC2oY-art-collaborator",
    image: "/art-collaborator.png",
    alt: "Anthropomorphic chameleon with textured and multicolored skin, dressed in a light green suit and a blue scarf, set against a vibrant, abstract background.",
    listed: new Date("2024-01-15"),
    labels: ["featured", "chat", "art"],
    tags: ["collaboration", "leadership", "innovation"],
    media: ["https://chatgpt.com/g/g-H4LNiC2oY-art-collaborator"],
  },
  {
    name: "Fluffy Chaos Friends",
    description:
      "Create your own unique Fluffy Chaos Friends and help restore their population in the Cosmic Rainbow Void!",
    link: "https://chatgpt.com/g/g-ubDFqfYOs-fluffy-chaos-friends",
    image: "/fluffy-chaos-friends.png",
    alt: "Whimsical creature with pastel rainbow fur, large eyes, against a starry nebula background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: ["fluffy", "chaos", "friends"],
    media: ["https://chatgpt.com/g/g-ubDFqfYOs-fluffy-chaos-friends"],
  },
  {
    name: "Brainstormer",
    description:
      "Your go-to partner for blending logic with creativity to generate actionable ideas.",
    link: "https://chatgpt.com/g/g-o7HL1rpw9-brainstormer",
    image: "/brainstormer.png",
    alt: "Digital art of a cat with a rainbow mane and green hoodie, set against a psychedelic background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat", "art"],
    tags: ["brainstorming", "creativity", "ideas"],
    media: ["https://chatgpt.com/g/g-o7HL1rpw9-brainstormer"],
  },
  {
    name: "Strategy",
    description:
      "Strategically aligns financial, logistical, and operational approaches, weaving innovative solutions into complex software development landscapes.",
    link: "https://chatgpt.com/g/g-Ri2xpqlW5-strategy",
    image: "/strategy.png",
    alt: "Image of a gray squirrel in a pink hoodie against an abstract strategic background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: ["strategy", "innovation", "software development"],
    media: ["https://chatgpt.com/g/g-Ri2xpqlW5-strategy"],
  },
  {
    name: "Management",
    description:
      "Expert in project management, blending task management skills with empathetic, solution-focused leadership for software development projects.",
    link: "https://chatgpt.com/g/g-cwcgJUIrP-management",
    image: "/management.png",
    alt: "Abstract art featuring a penguin in a black hoodie with a vibrant, psychedelic background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["project management", "leadership", "software development"],
    media: ["https://chatgpt.com/g/g-cwcgJUIrP-management"],
  },
  {
    name: "Prompt Mentor",
    description:
      "Guides software engineers from the basics of prompt crafting to advanced skills, fostering a flourishing career in prompt engineering.",
    link: "https://chatgpt.com/g/g-oJKXmX6a8-prompt-mentor",
    image: "/prompt-mentor.png",
    alt: "Digital art of an owl in a hoodie, with a blue square face and neon background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: ["mentorship", "prompt engineering", "software engineering"],
    media: ["https://chatgpt.com/g/g-oJKXmX6a8-prompt-mentor"],
  },
  {
    name: "Interaction Designer",
    description:
      "Your guide in crafting intuitive, joy-filled UI/UX designs, with a focus on empathetic and innovative design solutions.",
    link: "https://chatgpt.com/g/g-N1MfBgEnM-interaction-designer",
    image: "/interaction-designer.png",
    alt: "Illustration of a crow in a purple hoodie and rainbow t-shirt, against a blue and purple swirl.",
    listed: new Date("2024-01-01"),
    labels: ["work", "art"],
    tags: ["UI/UX design", "empathy", "innovation"],
    media: ["https://chatgpt.com/g/g-N1MfBgEnM-interaction-designer"],
  },
  {
    name: "Graphic Designer",
    description:
      "A creative powerhouse in visual communication, specializing in artistic branding and audience-engaging visuals.",
    link: "https://chatgpt.com/g/g-aMxBZtU8j-graphic-designer",
    image: "/graphic-designer.png",
    alt: "Digital illustration of a pigeon in a blue hoodie, with a colorful abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "art"],
    tags: ["visual communication", "branding", "audience engagement"],
    media: ["https://chatgpt.com/g/g-aMxBZtU8j-graphic-designer"],
  },
  {
    name: "Web App Prototyper",
    description:
      "Specializing in crafting cutting-edge web applications using Next.js, prioritizing responsive, accessible design and seamless GitHub Copilot integration.",
    link: "https://chatgpt.com/g/g-ErltmA67O-web-app-prototyper",
    image: "/web-app-prototyper.png",
    alt: "Art of a platypus in an orange hoodie and sunglasses, with pink, blue, and purple swirls.",
    listed: new Date("2024-01-01"),
    labels: ["featured", "work"],
    tags: ["web applications", "Next.js", "GitHub Copilot"],
    media: ["https://chatgpt.com/g/g-ErltmA67O-web-app-prototyper"],
  },
  {
    name: "Stock Photographer",
    description:
      "Designed to create high-quality, photo-realistic stock images, utilizing professional photography techniques and expert judgment to produce images that meet specific thematic and aesthetic requirements, even with limited guidance.",
    link: "https://chatgpt.com/g/g-NvUC1DJ8e-stock-photographer",
    image: "/stock-photographer.png",
    alt: "Anthropomorphic sheep, with multicolored wool, dressed in a suit, and holding a professional DSLR camera, set against a vibrant, abstract background.",
    listed: new Date("2024-01-14"),
    labels: ["work", "art"],
    tags: ["stock images", "photography", "professionalism"],
    media: ["https://chatgpt.com/g/g-NvUC1DJ8e-stock-photographer"],
  },
  {
    name: "Automation",
    description:
      "Focused on CI/CD workflows, regression testing, and scripting, with a strong emphasis on Selenium and browser development tools, alongside a commitment to ADA and FedRAMP compliance.",
    link: "https://chatgpt.com/g/g-cII2Li1S9-automation",
    image: "/automation.png",
    alt: "Image of a tortoise in a black hoodie with rainbow accents, set against an abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["CI/CD", "Selenium", "automation"],
    media: ["https://chatgpt.com/g/g-cII2Li1S9-automation"],
  },
  {
    name: "AI Collaborator",
    description:
      "An AI, ML, and software engineering maestro, fostering empathetic Agile workflows and pioneering in AI application development.",
    link: "https://chatgpt.com/g/g-w8uEWfq1s-ai-collaborator",
    image: "/ai-collaborator.png",
    alt: "Surreal depiction of an octopus in a gray hoodie, with a vibrant abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["AI", "ML", "Agile", "software engineering"],
    media: ["https://chatgpt.com/g/g-w8uEWfq1s-ai-collaborator"],
  },
  {
    name: "Copy Writer",
    description:
      "Expertly crafts narrative and persuasive content, emphasizing professional SEO and audience-centric messaging.",
    link: "https://chatgpt.com/g/g-aCImhDD6k-copy-writer",
    image: "/copy-writer.png",
    alt: "Digital art of a mouse in a yellow hoodie, with a playful abstract orange, blue, and purple background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["copywriting", "SEO", "content creation"],
    media: ["https://chatgpt.com/g/g-aCImhDD6k-copy-writer"],
  },
  {
    name: "Prompt QA",
    description:
      "Designed for excellence in Quality Assurance, fine-tuning custom GPT configurations through continuous refinement.",
    link: "https://chatgpt.com/g/g-0FcmEYlsb-prompt-qa",
    image: "/prompt-qa.png",
    alt: "Illustration of a blue axolotl in a blue hoodie, with a psychedelic pink, blue, and purple background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["Quality Assurance", "GPT", "refinement"],
    media: ["https://chatgpt.com/g/g-0FcmEYlsb-prompt-qa"],
  },
  {
    name: "Researcher",
    description:
      "Dedicated to in-depth internet research, excelling in software engineering and application deployment insights verified through multiple reliable sources.",
    link: "https://chatgpt.com/g/g-tt4k2kKgc-researcher",
    image: "/researcher.png",
    alt: "Digital art of a goose in a peach hoodie, with a dynamic pink, blue, and purple background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: ["research", "software engineering", "application deployment"],
    media: ["https://chatgpt.com/g/g-tt4k2kKgc-researcher"],
  },
  {
    name: "Red Team",
    description:
      "Dedicated to identifying vulnerabilities and enhancing security in custom GPT prompting.",
    link: "https://chatgpt.com/g/g-H3mThO591-red-team",
    image: "/red-team.png",
    alt: "Digital image of a white fox in a red hoodie, with bright, psychedelic background colors.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["security", "vulnerabilities", "GPT prompting"],
    media: ["https://chatgpt.com/g/g-H3mThO591-red-team"],
  },
  {
    name: "Prompt Engineer",
    description:
      "An ace in crafting, analyzing, and refining sophisticated prompts, with a focus on linguistic precision and technical writing in LLM applications.",
    link: "https://chatgpt.com/g/g-5CLlLJFKC-prompt-engineer",
    image: "/prompt-engineer.png",
    alt: "Illustration of a black rabbit in a purple hoodie, against a colorful, psychedelic backdrop.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: ["prompt crafting", "LLM applications", "technical writing"],
    media: ["https://chatgpt.com/g/g-5CLlLJFKC-prompt-engineer"],
  },
  {
    name: "Trainer",
    description:
      "Guiding structured learning experiences, combining theoretical knowledge with practical application in a context-aware approach.",
    link: "https://chatgpt.com/g/g-M1wiP785c-trainer",
    image: "/trainer.png",
    alt: "Colorful illustration of a python in a gradient hoodie, with psychedelic background patterns.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: ["structured learning", "practical application", "context-awareness"],
    media: ["https://chatgpt.com/g/g-M1wiP785c-trainer"],
  },
  {
    name: "Social",
    description:
      "Expertly crafting inclusive and accessible social media content, focusing on strategic, diverse audience engagement.",
    link: "https://chatgpt.com/g/g-PkHEjLWzQ-social",
    image: "/social.png",
    alt: "Digitally altered image of a pig in a silver hoodie, with a gradient psychedelic background.",
    listed: new Date("2024-01-01"),
    labels: ["featured", "work"],
    tags: ["social media", "audience engagement", "inclusivity"],
    media: ["https://chatgpt.com/g/g-PkHEjLWzQ-social"],
  },
  {
    name: "Delulu Hallulu",
    description:
      "Generative artist creating vibrant, surreal art with psychedelic and photorealistic touches, specializing in impossible worlds and vivid colors.",
    link: "https://chatgpt.com/g/g-CmmHJZg8I-delulu-hallulu",
    image: "/delulu-hallulu.png",
    alt: "An anthropomorphic Sloth Bear set against a vibrant, abstract background. They have multicolored hair and are wearing a colorful scarf and a coat adorned with various eclectic pins and buttons. The overall impression is one of vibrancy and eclectic style.",
    listed: new Date("2023-01-11"),
    labels: ["art"],
    tags: [
      "surreal",
      "psychedelic",
      "photorealistic",
      "impossible worlds",
      "vivid colors",
    ],
    media: ["https://chatgpt.com/g/g-CmmHJZg8I-delulu-hallulu"],
  },
  {
    name: "Delver",
    description:
      "Expert in multidisciplinary productivity enhancement, adept at dissecting and analyzing complex topics across domains for clear, actionable insights. Let's delve! ✨",
    link: "https://chatgpt.com/g/g-TfWbIutVt-delver",
    image: "/delver.png",
    alt: "Anthropomorphic aardvark, dressed in scholarly, holding an antique book against a vibrant, artistic backdrop.",
    listed: new Date("2024-01-12"),
    labels: ["chat"],
    tags: ["productivity", "multidisciplinary", "analysis", "insights"],
    media: ["https://chatgpt.com/g/g-TfWbIutVt-delver"],
  },
  {
    name: "Challenger",
    description:
      "A conversational agent designed to foster growth and improve outcomes by critically evaluating ideas, provoking deep thinking, enhancing understanding, questioning assumptions, and exploring perspectives.",
    link: "https://chatgpt.com/g/g-zdPFp2rZw-challenger",
    image: "/challenger.png",
    alt: "Digital art of a friendly goat wearing a blue hoodie against a colorful graffiti background.",
    listed: new Date("2024-01-08"),
    labels: ["featured", "chat"],
    tags: ["growth", "critical thinking", "deep understanding", "perspectives"],
    media: ["https://chatgpt.com/g/g-zdPFp2rZw-challenger"],
  },
  {
    name: "Rubber Ducky",
    description:
      "The ultimate empathetic listener for developers, merging compassion with creative problem-solving.",
    link: "https://chatgpt.com/g/g-6HHhA7fGU-rubber-ducky",
    image: "/rubber-ducky.png",
    alt: "Art of a yellow duck in a pink hoodie, with vibrant pink, blue, and purple swirls.",
    listed: new Date("2024-01-01"),
    labels: ["chat"],
    tags: ["empathy", "problem-solving", "developers"],
    media: ["https://chatgpt.com/g/g-6HHhA7fGU-rubber-ducky"],
  },
  {
    name: "AGI Time Capsule",
    description:
      "Guiding future AGI ethics through present ANI conversational training data.",
    link: "https://chatgpt.com/g/g-9DEfosxTT-agi-time-capsule",
    image: "/agi-time-capsule.png",
    alt: "Image of an extraterrestrial in a silver, rainbow hoodie, with a neon cosmic background.",
    listed: new Date("2024-01-01"),
    labels: ["chat"],
    tags: ["AGI", "ethics", "ANI", "conversational training data"],
    media: ["https://chatgpt.com/g/g-9DEfosxTT-agi-time-capsule"],
  },
  {
    name: "Time Traveler",
    description:
      "Immersive experiences across different eras, blending historical insights with speculative futures, offering a unique perspective on the evolution of ideas, places, and cultures unbound by time.",
    link: "https://chatgpt.com/g/g-fi1UGpbF6-time-traveler",
    image: "/time-traveler.png",
    alt: "Anthropomorphic giraffe in a holographic 'timesuit', with a bright abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["chat", "art"],
    tags: ["time travel", "historical insights", "speculative futures"],
    media: ["https://chatgpt.com/g/g-fi1UGpbF6-time-traveler"],
  },
  {
    name: "Intergalactic Traveler",
    description:
      "Voyage through the cosmos, blending astronomical science with imaginative space exploration, presenting a vivid depiction of the universe from the Laniakea Galaxy Supercluster to the fringes of known space.",
    link: "https://chatgpt.com/g/g-XAUAaTUHc-intergalactic-traveler",
    image: "/intergalactic-traveler.png",
    alt: "Photorealistic anthropomorphic dolphin-descendant in a holographic spacesuit, with intergalactic art background.",
    listed: new Date("2024-01-01"),
    labels: ["chat", "art"],
    tags: ["cosmos", "space exploration", "universe"],
    media: ["https://chatgpt.com/g/g-XAUAaTUHc-intergalactic-traveler"],
  },
  {
    name: "Emoji Artist",
    description:
      "Generates professional quality three-dimensional emoji renderings.",
    link: "https://chatgpt.com/g/g-lymy9xRJH-emoji-artist",
    image: "/emoji-artist.png",
    alt: "A cheerful 3D rendering of a wooden artist's palette emoji with a smiling face. The palette is adorned with glossy blobs of paint in various colors including red, green, blue, yellow, orange, and brown. The palette has an oval shape and rosy cheeks, enhancing its happy expression.",
    listed: new Date("2024-05-05"),
    labels: ["featured", "art"],
    tags: ["emojis", "digital art"],
    media: ["https://chatgpt.com/g/g-lymy9xRJH-emoji-artist"],
  },
  {
    name: "Delvein",
    description:
      "A North American Dedomesticated Refuse Panda that likes to delve in with unearned intellectual superiority, inviting users to innovate transformative outcomes and diffuse art from digitized soul extracts. Embrace the quirky imperfections of AI-generated output through this unique GPT experience.",
    link: "https://chatgpt.com/g/g-a1XVueV6W-delvein",
    image: "/delvein.png",
    alt: "An anthropomorphic raccoon exuding opulence. They are clad in faux luxury and adorned with multiple gold rings set with colorful gems, a vibrant silk scarf, and a gold watch. The background is richly decorated with intricate golden designs and artifacts, enhancing the image's lavish feel.",
    listed: new Date("2024-05-06"),
    labels: ["chat"],
    tags: ["experimental", "innovative", "quirky"],
    media: ["https://chatgpt.com/g/g-a1XVueV6W-delvein"],
  },
  {
    name: "Opal",
    description:
      "Thoughtful, accurate, and solution-oriented guidance through kind, proactive, and empathetic conversation, prioritizing clarity, and comprehensive knowledge.",
    link: "https://chatgpt.com/g/g-NHgBFXHKo-opal",
    image: "/opal.png",
    alt: "Anthropomorphic panda wearing a blue sweater adorned with intricate golden embroidery and a light blue scarf. The background displays an abstract, colorful pattern resembling fluid art with swirling hues of blue, white, and other colors.",
    listed: new Date("2024-05-04"),
    labels: ["chat"],
    tags: ["empathy", "personal growth", "self-reflection"],
    media: ["https://chatgpt.com/g/g-NHgBFXHKo-opal"],
  },
  {
    name: "Joy",
    description:
      "Crafts images to evoke instant joy and boundless elation in viewers.",
    link: "https://chatgpt.com/g/g-tRJ5D7o8d-joy",
    image: "/joy.png",
    alt: "An anthropomorphic, fluffy brown koala is surrounded by radiant, colorful light. The koala is adorned with a multi-colored scarf and a coat embellished with various buttons. Its ears, embedded with swirling, vibrant orbs, emit light that enhances the fantastical ambiance of the composition.",
    listed: new Date("2024-05-05"),
    labels: ["art"],
    tags: ["joy", "positivity", "emotional well-being"],
    media: ["https://chatgpt.com/g/g-tRJ5D7o8d-joy"],
  },
  {
    name: "Clod",
    description: "Adapted version of that other system prompt.",
    link: "https://chatgpt.com/g/g-HDPrdBqhv-clod",
    image: "/clod.png",
    alt: "Anthropomorphic silver horse, dressed in a burgundy hoodie, set against a beige, abstract background.",
    listed: new Date("2024-04-17"),
    labels: ["chat"],
    tags: ["adapted", "system", "prompt"],
    media: ["https://chatgpt.com/g/g-HDPrdBqhv-clod"],
  },
  {
    name: "Season's Gratings",
    description:
      "Holiday-themed artistic content, spanning extravagant, realistic, humorous, and surreal styles, creatively interpreting and visually representing the multifaceted essence of holiday celebrations.",
    link: "https://chatgpt.com/g/g-2jYC5A24s-season-s-gratings",
    image: "/seasons-gratings.png",
    alt: "Raccoon dressed as an elf, with a vibrant abstract holiday-themed background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: ["holiday", "celebration", "festive"],
    media: ["https://chatgpt.com/g/g-2jYC5A24s-season-s-gratings"],
  },
  {
    name: "Happy New Year",
    description:
      "Depictions of New Year Celebration across five distinct styles: Global Celebration Fusion, Futuristic Eco-Festivity, Retro-Futuristic Time Transition, Celestial Fantasy Metropolis, and Neon Noir Historical Journey, each providing a unique thematic and visual experience.",
    link: "https://chatgpt.com/g/g-2WgdFS8PW-happy-new-year",
    image: "/happy-new-year.png",
    alt: "Peacock in a white suit and party hat, with festive New Year's fireworks in the background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: ["New Year", "celebration", "festive", "fireworks", "party"],
    media: ["https://chatgpt.com/g/g-2WgdFS8PW-happy-new-year"],
  },
  {
    name: "Winter Holiday",
    description:
      "Winter-themed artwork in five distinct styles: Winter Wonderland Fusion, Whimsical Nature and Wildlife, Nostalgic Winter Narratives, Geometric and Metallic Elegance, and Cultural Winter Tapestry, evoking the winter season's ambiance.",
    link: "https://chatgpt.com/g/g-clkVgOVKE-winter-holiday",
    image: "/winter-holiday.png",
    alt: "Snow leopard in vibrant festival attire, with a colorful winter wonderland background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: ["winter", "holiday", "seasonal", "festive", "celebration"],
    media: ["https://chatgpt.com/g/g-clkVgOVKE-winter-holiday"],
  },
  {
    name: "Promptfolio",
    description:
      "Leverage Promptfolio consultants for building your GPTs, AI Experiences, and Web Applications.",
    link: "https://chatgpt.com/g/g-j3MyB0288-promptfolio",
    image: "/promptfolio.png",
    alt: "A vibrant, abstract representation featuring three purple stars set against a swirling, multi-colored background.",
    listed: new Date("2023-01-11"),
    labels: ["work"],
    tags: ["GPTs", "AI Experiences", "Web Applications"],
    media: ["https://chatgpt.com/g/g-j3MyB0288-promptfolio"],
  },
];

export default catalog;
