// lib/catalog.ts
export const catalog = [
  {
    name: "Season's Gratings",
    description:
      "Holiday-themed artistic content, spanning extravagant, realistic, humorous, and surreal styles, creatively interpreting and visually representing the multifaceted essence of holiday celebrations.",
    link: "https://chat.openai.com/g/g-2jYC5A24s-season-s-gratings",
    image: "/seasons-gratings.png",
    alt: "An anthropomorphic raccoon with realistic fur and a mischievous smile, dressed as Santa's helper in a red and green elf costume, including a pointed hat. The background features a vivid abstract explosion of colors with winter holiday elements like snowflakes and ornaments.",
    listed: new Date("2023-12-23"),
    labels: ["featured", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Happy New Year 2024",
    description:
      "Depictions of New Year 2024 across five distinct styles: Global Celebration Fusion, Futuristic Eco-Festivity, Retro-Futuristic Time Transition, Celestial Fantasy Metropolis, and Neon Noir Historical Journey, each providing a unique thematic and visual experience.",
    link: "https://chat.openai.com/g/g-2WgdFS8PW-happy-new-year-2024",
    image: "/happy-new-year-2024.png",
    alt: "An anthropomorphic peacock with vibrant blue feathers and a playful expression, wearing a fancy white suit with a colorful bow tie and a party hat, ready for a New Year's Eve celebration. The background is a kaleidoscope of abstract colors with New Year's fireworks, adding a festive atmosphere to the portrait.",
    listed: new Date("2023-12-23"),
    labels: ["featured", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Brainstormer",
    description:
      "Your go-to partner for blending logic with creativity to generate actionable ideas.",
    link: "https://chat.openai.com/g/g-o7HL1rpw9-brainstormer",
    image: "/brainstormer.png",
    alt: "This image is a digital art representation of a cat with a rainbow-colored mane and bright green eyes, wearing a green hoodie. The cat's mane appears to be made up of flames in a spectrum of rainbow colors. The background is a psychedelic swirl of various colors and shapes, adding to the overall vibrant and surreal aesthetic of the image. The cat's nose is depicted in a contrasting pink color. The green hoodie worn by the cat has a zipper detail down the front, adding a touch of realism to this otherwise fantastical image.",
    listed: new Date("2024-01-01"),
    labels: ["featured", "work", "chat", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Strategy",
    description:
      "Strategically aligns financial, logistical, and operational approaches, weaving innovative solutions into complex software development landscapes.",
    link: "https://chat.openai.com/g/g-Ri2xpqlW5-strategy",
    image: "/strategy.png",
    alt: "A fluffy gray squirrel in a soft pink hoodie, embodying thoughtful and adaptive strategic planning, set against an abstract background that reflects the multifaceted nature of strategic thinking.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Management",
    description:
      "Expert in project management, blending task management skills with empathetic, solution-focused leadership for software development projects.",
    link: "https://chat.openai.com/g/g-cwcgJUIrP-management",
    image: "/management.png",
    alt: "This is a surreal and abstract image featuring a penguin in a black hoodie. The background is a vibrant mix of rainbow colors with swirling patterns, interspersed with various shapes and objects such as spheres and lines. The overall mood of the image is psychedelic, creating a dreamlike atmosphere.",
    listed: new Date("2024-01-01"),
    labels: ["featured", "work"],
    tags: [],
    media: [],
  },
  {
    name: "Prompt Mentor",
    description:
      "Guides software engineers from the basics of prompt crafting to advanced skills, fostering a flourishing career in prompt engineering.",
    link: "https://chat.openai.com/g/g-oJKXmX6a8-prompt-mentor",
    image: "/prompt-mentor.png",
    alt: "This is a digital art image featuring an owl wearing a hoodie. The owl's face is obscured by a blue square, and its eyes are glowing green. The hoodie is pink and adorned with blue birds. The background is filled with neon colors and lines, creating a vibrant and dynamic atmosphere.",
    listed: new Date("2024-01-01"),
    labels: ["featured", "work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Interaction Designer",
    description:
      "Your guide in crafting intuitive, joy-filled UI/UX designs, with a focus on empathetic and innovative design solutions.",
    link: "https://chat.openai.com/g/g-N1MfBgEnM-interaction-designer",
    image: "/interaction-designer.png",
    alt: "This image is a digital illustration of a crow wearing a purple hoodie. The crow has a large beak and expressive eyes. The background is a colorful swirl of blue and purple. The crow is also wearing a t-shirt with a rainbow design on it. The hoodie is purple with a white drawstring.",
    listed: new Date("2024-01-01"),
    labels: ["work", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Graphic Designer",
    description:
      "A creative powerhouse in visual communication, specializing in artistic branding and audience-engaging visuals.",
    link: "https://chat.openai.com/g/g-aMxBZtU8j-graphic-designer",
    image: "/graphic-designer.png",
    alt: "This image is a digital illustration of a pigeon wearing a blue hoodie. The pigeon, facing the viewer, has a white beak and orange eyes. The background is a colorful abstract swirl of colors, including red, orange, yellow, blue, and green, with a few scattered feathers adding to the whimsical nature of the image.",
    listed: new Date("2024-01-01"),
    labels: ["work", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Web App Prototyper",
    description:
      "Specializing in crafting cutting-edge web applications using Next.js, prioritizing responsive, accessible design and seamless GitHub Copilot integration.",
    link: "https://chat.openai.com/g/g-ErltmA67O-web-app-prototyper",
    image: "/web-app-prototyper.png",
    alt: "This is a digital art image featuring a platypus wearing an orange hoodie and sunglasses. The background is filled with swirls of pink, blue, and purple, creating a vibrant and dynamic atmosphere.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Automation",
    description:
      "Focused on CI/CD workflows, regression testing, and scripting, with a strong emphasis on Selenium and browser development tools, alongside a commitment to ADA and FedRAMP compliance.",
    link: "https://chat.openai.com/g/g-cII2Li1S9-automation",
    image: "/automation.png",
    alt: "A tortoise in a black hoodie with rainbow accents, symbolizing precision and depth, set against an abstract background representing the complexity of automation in software development.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "AI Collaborator",
    description:
      "An AI, ML, and software engineering maestro, fostering empathetic Agile workflows and pioneering in AI application development.",
    link: "https://chat.openai.com/g/g-w8uEWfq1s-ai-collaborator",
    image: "/ai-collaborator.png",
    alt: "This image features a surreal depiction of an octopus with a human-like body, wearing a gray hoodie. The octopus has a large head with multiple eyes and tentacles. The background is an abstract painting with a vibrant mix of orange, yellow, and blue colors. The image has a 3D effect, making the octopus appear as if it's emerging from the background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Copy Writer",
    description:
      "Expertly crafts narrative and persuasive content, emphasizing SEO optimization and audience-centric messaging.",
    link: "https://chat.openai.com/g/g-aCImhDD6k-copy-writer",
    image: "/copy-writer.png",
    alt: "This image is a digital illustration of a mouse wearing a yellow hoodie. The mouse has large round ears, a pointed nose, and long whiskers. The hoodie is yellow with a zipper down the front. The background is a colorful abstract design with swirls of orange, blue, and purple. The overall mood of the image is playful and whimsical.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "GPT QA",
    description:
      "Designed for excellence in Quality Assurance, fine-tuning custom GPT configurations through continuous refinement.",
    link: "https://chat.openai.com/g/g-0FcmEYlsb-gpt-qa",
    image: "/gpt-qa.png",
    alt: "This image is a digital illustration of a blue axolotl wearing a hoodie. The axolotl, characterized by its blue body and white face, has black eyes and a pink mouth. It's wearing a blue hoodie with a zipper in the front. The background is a psychedelic swirl of pink, blue, and purple colors. The axolotl is facing the viewer and appears to be smiling, adding a playful and whimsical mood to the image.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Researcher",
    description:
      "Dedicated to in-depth internet research, excelling in software engineering and application deployment insights verified through multiple reliable sources.",
    link: "https://chat.openai.com/g/g-tt4k2kKgc-researcher",
    image: "/researcher.png",
    alt: "This is a digital art image featuring a goose wearing a peach hoodie. The background is filled with swirls of pink, blue, and purple, creating a vibrant and dynamic atmosphere.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Red Team",
    description:
      "Dedicated to identifying vulnerabilities and enhancing security in custom GPT prompting.",
    link: "https://chat.openai.com/g/g-H3mThO591-red-team",
    image: "/red-team.png",
    alt: "This is a digital art image featuring a fox with white fur and pointy ears, and it's wearing a red hoodie with a gradient pattern. The background is filled with bright colors and psychedelic swirls, creating a vibrant and dynamic atmosphere.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Prompt Engineer",
    description:
      "An ace in crafting, analyzing, and refining sophisticated prompts, with a focus on linguistic precision and technical writing in LLM applications.",
    link: "https://chat.openai.com/g/g-5CLlLJFKC-prompt-engineer",
    image: "/prompt-engineer.png",
    alt: "This is a digital illustration featuring a black rabbit wearing a purple hoodie. The rabbit's fur is shiny and its ears are pointed upwards. The hoodie is detailed with a white zipper and strings. The background of the image is filled with colorful, psychedelic swirls and curls in various hues. This vibrant backdrop enhances the overall visual appeal of the illustration, making it a captivating piece of digital art.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Trainer",
    description:
      "Guiding structured learning experiences, combining theoretical knowledge with practical application in a context-aware approach.",
    link: "https://chat.openai.com/g/g-M1wiP785c-trainer",
    image: "/trainer.png",
    alt: "This is a colorful illustration of a python wearing a purple and green gradient hoodie. The background is filled with psychedelic swirls and patterns.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Social",
    description:
      "Expertly crafting inclusive and accessible social media content, focusing on strategic, diverse audience engagement.",
    link: "https://chat.openai.com/g/g-PkHEjLWzQ-social",
    image: "/social.png",
    alt: "This is a digitally altered image featuring a pig wearing a silver hoodie. The background is a colorful psychedelic pattern with a gradient of blue, green, pink, and yellow. The silver hoodie worn by the pig adds a contrasting element to the vibrant background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Rubber Ducky",
    description:
      "The ultimate empathetic listener for developers, merging compassion with creative problem-solving.",
    link: "https://chat.openai.com/g/g-6HHhA7fGU-rubber-ducky",
    image: "/rubber-ducky.png",
    alt: "This is a digital art image featuring yellow duck wearing a pink hoodie. The background is filled with swirls of pink, blue, and purple, creating a vibrant and dynamic atmosphere. The duck is facing forward and their body is visible from the chest up.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "AGI Time Capsule",
    description:
      "Guiding future AGI ethics through present ANI conversational training data.",
    link: "https://chat.openai.com/g/g-9DEfosxTT-agi-time-capsule",
    image: "/agi-time-capsule.png",
    alt: "This is a digitally altered image featuring an extraterrestrial with a serene expression, wearing a silver hoodie with a rainbow-colored sheen. The entity has large, almond-shaped eyes that resemble star-filled galaxies, giving it a wise and mystical appearance. The background is a vibrant, kaleidoscopic array of neon colors and cosmic motifs, including stars, nebulae-like swirls, and glowing geometric shapes, all contributing to a sense of otherworldly wonder.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
];

export default catalog;
