// lib/catalog.ts
export const catalog = [
  {
    name: "Alchemist",
    description:
      "Transforms output quality with a magical blend of precision, creativity, and context-awareness, integrating advanced prompt engineering for detailed, relevant, and accurate responses.",
    link: "https://chat.openai.com/g/g-IGIy9zqun-alchemist",
    image: "/alchemist.png",
    alt: " A vibrant, anthropomorphic butterfly with intricate patterns and jewelry, extending a hand in an ethereal, colorfully lit atmosphere.",
    listed: new Date("2023-01-11"),
    labels: ["featured", "chat", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Robot Photographer",
    description:
      "Crafting striking, photorealistic scenes, this agent merges vivid, anthropomorphic robots and humans in imaginative, HDR-rich environments, blurring reality with creative storytelling.",
    link: "https://chat.openai.com/g/g-ID1XA2jXX-robot-photographer",
    image: "/robot-photographer.png",
    alt: "A metallic blue and gold robot, set against a vibrant, psychedelic background.",
    listed: new Date("2024-01-14"),
    labels: ["featured", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Art Collaborator",
    description:
      "Crafted for active engagement and leadership in visual and written arts, combining expert guidance with advocacy for creative goals and challenging conventional ideas to foster innovation and exploration.",
    link: "https://chat.openai.com/g/g-H4LNiC2oY-art-collaborator",
    image: "/art-collaborator.png",
    alt: "Anthropomorphic chameleon with textured and multicolored skin, dressed in a light green suit and a blue scarf, set against a vibrant, abstract background.",
    listed: new Date("2024-01-15"),
    labels: ["featured", "chat", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Fluffy Chaos Friends",
    description:
      "Create your own unique Fluffy Chaos Friends and help restore their population in the Cosmic Rainbow Void!",
    link: "https://chat.openai.com/g/g-ubDFqfYOs-fluffy-chaos-friends",
    image: "/fluffy-chaos-friends.png",
    alt: "Whimsical creature with pastel rainbow fur, large eyes, against a starry nebula background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: [],
    media: [],
  },
  {
    name: "Brainstormer",
    description:
      "Your go-to partner for blending logic with creativity to generate actionable ideas.",
    link: "https://chat.openai.com/g/g-o7HL1rpw9-brainstormer",
    image: "/brainstormer.png",
    alt: "Digital art of a cat with a rainbow mane and green hoodie, set against a psychedelic background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Strategy",
    description:
      "Strategically aligns financial, logistical, and operational approaches, weaving innovative solutions into complex software development landscapes.",
    link: "https://chat.openai.com/g/g-Ri2xpqlW5-strategy",
    image: "/strategy.png",
    alt: "Image of a gray squirrel in a pink hoodie against an abstract strategic background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Management",
    description:
      "Expert in project management, blending task management skills with empathetic, solution-focused leadership for software development projects.",
    link: "https://chat.openai.com/g/g-cwcgJUIrP-management",
    image: "/management.png",
    alt: "Abstract art featuring a penguin in a black hoodie with a vibrant, psychedelic background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Prompt Mentor",
    description:
      "Guides software engineers from the basics of prompt crafting to advanced skills, fostering a flourishing career in prompt engineering.",
    link: "https://chat.openai.com/g/g-oJKXmX6a8-prompt-mentor",
    image: "/prompt-mentor.png",
    alt: "Digital art of an owl in a hoodie, with a blue square face and neon background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Interaction Designer",
    description:
      "Your guide in crafting intuitive, joy-filled UI/UX designs, with a focus on empathetic and innovative design solutions.",
    link: "https://chat.openai.com/g/g-N1MfBgEnM-interaction-designer",
    image: "/interaction-designer.png",
    alt: "Illustration of a crow in a purple hoodie and rainbow t-shirt, against a blue and purple swirl.",
    listed: new Date("2024-01-01"),
    labels: ["work", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Graphic Designer",
    description:
      "A creative powerhouse in visual communication, specializing in artistic branding and audience-engaging visuals.",
    link: "https://chat.openai.com/g/g-aMxBZtU8j-graphic-designer",
    image: "/graphic-designer.png",
    alt: "Digital illustration of a pigeon in a blue hoodie, with a colorful abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Web App Prototyper",
    description:
      "Specializing in crafting cutting-edge web applications using Next.js, prioritizing responsive, accessible design and seamless GitHub Copilot integration.",
    link: "https://chat.openai.com/g/g-ErltmA67O-web-app-prototyper",
    image: "/web-app-prototyper.png",
    alt: "Art of a platypus in an orange hoodie and sunglasses, with pink, blue, and purple swirls.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Stock Photographer",
    description:
      "Designed to create high-quality, photo-realistic stock images, utilizing professional photography techniques and expert judgment to produce images that meet specific thematic and aesthetic requirements, even with limited guidance.",
    link: "https://chat.openai.com/g/g-NvUC1DJ8e-stock-photographer",
    image: "/stock-photographer.png",
    alt: "Anthropomorphic sheep, with multicolored wool, dressed in a suit, and holding a professional DSLR camera, set against a vibrant, abstract background.",
    listed: new Date("2024-01-14"),
    labels: ["work", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Automation",
    description:
      "Focused on CI/CD workflows, regression testing, and scripting, with a strong emphasis on Selenium and browser development tools, alongside a commitment to ADA and FedRAMP compliance.",
    link: "https://chat.openai.com/g/g-cII2Li1S9-automation",
    image: "/automation.png",
    alt: "Image of a tortoise in a black hoodie with rainbow accents, set against an abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "AI Collaborator",
    description:
      "An AI, ML, and software engineering maestro, fostering empathetic Agile workflows and pioneering in AI application development.",
    link: "https://chat.openai.com/g/g-w8uEWfq1s-ai-collaborator",
    image: "/ai-collaborator.png",
    alt: "Surreal depiction of an octopus in a gray hoodie, with a vibrant abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Copy Writer",
    description:
      "Expertly crafts narrative and persuasive content, emphasizing SEO optimization and audience-centric messaging.",
    link: "https://chat.openai.com/g/g-aCImhDD6k-copy-writer",
    image: "/copy-writer.png",
    alt: "Digital art of a mouse in a yellow hoodie, with a playful abstract orange, blue, and purple background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Prompt QA",
    description:
      "Designed for excellence in Quality Assurance, fine-tuning custom GPT configurations through continuous refinement.",
    link: "https://chat.openai.com/g/g-0FcmEYlsb-prompt-qa",
    image: "/prompt-qa.png",
    alt: "Illustration of a blue axolotl in a blue hoodie, with a psychedelic pink, blue, and purple background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Researcher",
    description:
      "Dedicated to in-depth internet research, excelling in software engineering and application deployment insights verified through multiple reliable sources.",
    link: "https://chat.openai.com/g/g-tt4k2kKgc-researcher",
    image: "/researcher.png",
    alt: "Digital art of a goose in a peach hoodie, with a dynamic pink, blue, and purple background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Red Team",
    description:
      "Dedicated to identifying vulnerabilities and enhancing security in custom GPT prompting.",
    link: "https://chat.openai.com/g/g-H3mThO591-red-team",
    image: "/red-team.png",
    alt: "Digital image of a white fox in a red hoodie, with bright, psychedelic background colors.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Prompt Engineer",
    description:
      "An ace in crafting, analyzing, and refining sophisticated prompts, with a focus on linguistic precision and technical writing in LLM applications.",
    link: "https://chat.openai.com/g/g-5CLlLJFKC-prompt-engineer",
    image: "/prompt-engineer.png",
    alt: "Illustration of a black rabbit in a purple hoodie, against a colorful, psychedelic backdrop.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Trainer",
    description:
      "Guiding structured learning experiences, combining theoretical knowledge with practical application in a context-aware approach.",
    link: "https://chat.openai.com/g/g-M1wiP785c-trainer",
    image: "/trainer.png",
    alt: "Colorful illustration of a python in a gradient hoodie, with psychedelic background patterns.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Social",
    description:
      "Expertly crafting inclusive and accessible social media content, focusing on strategic, diverse audience engagement.",
    link: "https://chat.openai.com/g/g-PkHEjLWzQ-social",
    image: "/social.png",
    alt: "Digitally altered image of a pig in a silver hoodie, with a gradient psychedelic background.",
    listed: new Date("2024-01-01"),
    labels: ["work"],
    tags: [],
    media: [],
  },
  {
    name: "Delulu Hallulu",
    description:
      "Generative artist creating vibrant, surreal art with psychedelic and photorealistic touches, specializing in impossible worlds and vivid colors.",
    link: "https://chat.openai.com/g/g-CmmHJZg8I-delulu-hallulu",
    image: "/delulu-hallulu.png",
    alt: "An anthropomorphic Sloth Bear set against a vibrant, abstract background. They have multicolored hair and are wearing a colorful scarf and a coat adorned with various eclectic pins and buttons. The overall impression is one of vibrancy and eclectic style.",
    listed: new Date("2023-01-11"),
    labels: ["featured", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Delver",
    description:
      "Expert in multidisciplinary productivity enhancement, adept at dissecting and analyzing complex topics across domains for clear, actionable insights. Let's delve! ✨",
    link: "https://chat.openai.com/g/g-TfWbIutVt-delver",
    image: "/delver.png",
    alt: "Anthropomorphic aardvark, dressed in scholarly, holding an antique book against a vibrant, artistic backdrop.",
    listed: new Date("2024-01-12"),
    labels: ["featured", "work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Challenger",
    description:
      "A conversational agent designed to foster growth and improve outcomes by critically evaluating ideas, provoking deep thinking, enhancing understanding, questioning assumptions, and exploring perspectives.",
    link: "https://chat.openai.com/g/g-zdPFp2rZw-challenger",
    image: "/challenger.png",
    alt: "A goat in a blue hoodie against a colorful graffiti background.",
    listed: new Date("2024-01-08"),
    labels: ["featured", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Rubber Ducky",
    description:
      "The ultimate empathetic listener for developers, merging compassion with creative problem-solving.",
    link: "https://chat.openai.com/g/g-6HHhA7fGU-rubber-ducky",
    image: "/rubber-ducky.png",
    alt: "Art of a yellow duck in a pink hoodie, with vibrant pink, blue, and purple swirls.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "AGI Time Capsule",
    description:
      "Guiding future AGI ethics through present ANI conversational training data.",
    link: "https://chat.openai.com/g/g-9DEfosxTT-agi-time-capsule",
    image: "/agi-time-capsule.png",
    alt: "Image of an extraterrestrial in a silver, rainbow hoodie, with a neon cosmic background.",
    listed: new Date("2024-01-01"),
    labels: ["work", "chat"],
    tags: [],
    media: [],
  },
  {
    name: "Time Traveler",
    description:
      "Immersive experiences across different eras, blending historical insights with speculative futures, offering a unique perspective on the evolution of ideas, places, and cultures unbound by time.",
    link: "https://chat.openai.com/g/g-fi1UGpbF6-time-traveler",
    image: "/time-traveler.png",
    alt: "Anthropomorphic giraffe in a holographic 'timesuit', with a bright abstract background.",
    listed: new Date("2024-01-01"),
    labels: ["chat", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Intergalactic Traveler",
    description:
      "Voyage through the cosmos, blending astronomical science with imaginative space exploration, presenting a vivid depiction of the universe from the Laniakea Galaxy Supercluster to the fringes of known space.",
    link: "https://chat.openai.com/g/g-XAUAaTUHc-intergalactic-traveler",
    image: "/intergalactic-traveler.png",
    alt: "Photorealistic anthropomorphic dolphin-descendant in a holographic spacesuit, with intergalactic art background.",
    listed: new Date("2024-01-01"),
    labels: ["chat", "art"],
    tags: [],
    media: [],
  },
  {
    name: "Season's Gratings",
    description:
      "Holiday-themed artistic content, spanning extravagant, realistic, humorous, and surreal styles, creatively interpreting and visually representing the multifaceted essence of holiday celebrations.",
    link: "https://chat.openai.com/g/g-2jYC5A24s-season-s-gratings",
    image: "/seasons-gratings.png",
    alt: "Raccoon dressed as an elf, with a vibrant abstract holiday-themed background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: [],
    media: [],
  },
  {
    name: "Happy New Year",
    description:
      "Depictions of New Year Celebration across five distinct styles: Global Celebration Fusion, Futuristic Eco-Festivity, Retro-Futuristic Time Transition, Celestial Fantasy Metropolis, and Neon Noir Historical Journey, each providing a unique thematic and visual experience.",
    link: "https://chat.openai.com/g/g-2WgdFS8PW-happy-new-year",
    image: "/happy-new-year.png",
    alt: "Peacock in a white suit and party hat, with festive New Year's fireworks in the background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: [],
    media: [],
  },
  {
    name: "Winter Holiday",
    description:
      "Winter-themed artwork in five distinct styles: Winter Wonderland Fusion, Whimsical Nature and Wildlife, Nostalgic Winter Narratives, Geometric and Metallic Elegance, and Cultural Winter Tapestry, evoking the winter season's ambiance.",
    link: "https://chat.openai.com/g/g-clkVgOVKE-winter-holiday",
    image: "/winter-holiday.png",
    alt: "Snow leopard in vibrant festival attire, with a colorful winter wonderland background.",
    listed: new Date("2023-12-23"),
    labels: ["art"],
    tags: [],
    media: [],
  },
  {
    name: "Promptfolio",
    description:
      "Leverage Promptfolio consultants for building your GPTs, AI Experiences, and Web Applications.",
    link: "https://chat.openai.com/g/g-j3MyB0288-promptfolio",
    image: "/promptfolio.png",
    alt: "A vibrant, abstract representation featuring three purple stars set against a swirling, multi-colored background.",
    listed: new Date("2023-01-11"),
    labels: ["work"],
    tags: [],
    media: [],
  },
];

export default catalog;
